name: C++ CI

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.arch == 'arm64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ git

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -j 4

    - name: Run benchmarks
      run: ./build/bin/BenchMath

  macos:
    strategy:
      matrix:
        include:
          - os: macos-14

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -j 4

    - name: Run benchmarks
      run: ./build/bin/BenchMath
